### ISSUE TITLE
[⬇️ Pre-Drop] Project Sakura Alpha Milestone 1 (working title)

### ISSUE THREAD

**Issue by openekun** [OPENet-Studios/Project-Sakura#1]
### What's your solution or idea?

- [ ] Change the core from vanilia into Quilt
- [ ] Install optimization mods
- [ ] Design a server icon
- [ ] Modify server configs
- [ ] Final adjustment & QoL improvements

### Relevant Assets

Will release this version before July 31, 2023 (UTC+8), so stay turn!
You can comment for that version plan; if you want to report bugs or request some features, please open another Issue.
